openapi: 3.1.0
info:
  title: Contract Calculator API
  description: Provides RESTful API for the Contract Calculator tool.
  version: 1.0.0
servers:
  - url: 'https://localhost/api/tools'

components:
  schemas:
    RequestedRemuneration:
      type: object
      properties:
        salary:
          type: integer
          description: The requested salary
        bonus:
          type: integer
          description: The requested bonus

    YearlyFigure:
      type: object
      properties:
        year:
          type: integer
          description: The year of this suggested contract
          minimum: 1
          maximum: 6
        salary:
          type: integer
          description: The salary for this year of the suggested contract
        yearlyRemuneration:
          type: integer
          description: The yearly remuneration for this year of the suggested contract

    SuggestedContract:
      type: object
      properties:
        years:
          type: integer
          description: The number of years of the suggested contract.
        totalSalary:
          type: integer
          description: The total salary for this suggested contract.
        bonusPerYear:
          type: integer
          description: The bonus per year for this suggested contract.
        totalRemuneration:
          type: integer
          description: The total remuneration over this suggested contract, salary and bonus combined.
        yearlyFigures:
          type: array
          minItems: 2
          maxItems: 6
      items:
        $ref: '#/components/schemas/YearlyFigure'

    SuggestedContracts:
      type: array
      minItems: 6
      maxItems: 6
      items:
        $ref: '#/components/schemas/SuggestedContract'

    Error:
      type: string

paths:
  /contract-calculator:
    post:
      summary: Returns a list of suggested contract values based upon a provided salary and bonus value.
      description: For given salary and bonus values, provides a range of contract offers from 2 to 6 years.
      requestBody:
        description: The requested salary and bonus for the suggested contracts
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestedRemuneration'
      responses:
        '200':
          description: Contracts generated and returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuggestedContracts'
        '4XX':
          description: Error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '5XX':
          description: Error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'